#!/usr/bin/env bash

#The MIT License (MIT)

#Copyright (c) 2015-2020 Dylan Araps

#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# Script Originally Created by Gamegenorator (https://github.com/Gamegenorator)

echo "Beginning Process..."
# Update System
echo "Installing System Updates"
sudo apt update
sudo apt-get dist-upgrade
sudo apt install
# Install git
echo "Installing git"
sudo apt install git
# Installing Snap Packager (Required for some things like Bitwarden)
sudo apt install snapd
# Install neofetch (You could just run 'apt install neofetch' but the snap is out of date)
echo "Installing Neofetch"
mkdir ~/.neofetch
cd ~/.neofetch
git clone https://github.com/dylanaraps/neofetch
sudo make install
cd ~/
# Install lolcat
echo "Installing lolcat"
sudo apt install ruby
sudo gem install lolcat
# Install cmatrix
echo "Installing cmatrix"
mkdir ~/.cmatrix
cd ~/.cmatrix
git clone https://github.com/abishekvashok/cmatrix.git
autoreconf -i
./configure
make
make install
# Install Htop
echo "Installing Htop"
sudo apt install htop
# Install Evolution Email Client
echo "Installing Evolution Email"
sudo apt install evolution
# Install Bitwarden Password Manager
echo "Installing Bitwarden Password Manager"
sudo snap install bitwarden
# Install KeePassXC Password Manager
echo "Installing KeePassXC"
sudo apt install keepassxc
# Install BleachBit
echo "Installing BleachBit"
sudo apt install bleachbit
# Install Blender
echo Installing Blender
sudo apt install blender
# Install Kdenlive
echo "Installing Kdenlive"
sudo apt install kdenlive
# Install Typora Markdown Editor
echo "Installing Typora markdown editor"
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update
sudo apt-get install typora
# Install Vim
echo "Installing Vim"
sudo apt install vim
# Install VSCodium
echo "Installing VSCodium"
cd ~/Downloads
wget -O codium_1.42.1-1581651960_amd64.deb https://github.com/VSCodium/vscodium/releases/download/1.42.1/codium_1.42.1-1581651960_amd64.deb
sudo dpkg -i codium_1.42.1-1581651960_amd64.deb
rm codium_1.42.1-1581651960_amd64.deb
cd ~/
# Install Atom Editor
echo "Installing Atom Code Editor"
cd ~/Downloads
wget -O atom-amd64.deb https://github.com/atom/atom/releases/download/v1.44.0/atom-amd64.deb
sudo dpkg -i atom-amd64.deb
rm atom-amd64.deb
cd ~/
# Install Sublime Text & Merge
echo "Preparing to install Sublime Text & Merge"
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
echo "Installing Sublime Text"
sudo apt-get install sublime-text
echo "Installing Sublime Merge"
sudo apt-get install sublime-merge
# Install Brave Browser
echo "Installing the Brave Browser"
sudo apt install apt-transport-https curl
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser
# Install newest version of NodeJS 12 LTS
echo "Installing NodeJS 12"
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install gcc g++ make
sudo npm install -g
node --version
npm --version
# Install Yarm
echo "Installing yarn"
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
# Install Electron (Requires Nodejs)
echo "Installing Electronjs"
npm install electron -g
# Install ReactNative (Requires Nodejs)
echo "Installing React-Native"
sudo npm i -g create-react-app
npm install -g expo-cli
# Install Redux (Requires Nodejs)
echo "Installing redux"
npm install redux
npm install react-redux
# Cleanup
echo "Cleanning Up..."
sudo apt autoremove
echo
# Done
echo "Done!"
echo "We Hope this was useful for you!"
echo "Script created by Gamegenorator <https://Github.com/Gamegenorator>"
echo
read -p "Press enter to close... "
